<a href="https://colab.research.google.com/github/RoihansLab/Data-Mining-Project/blob/main/Volcano_eruption.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**1. PROBLEM**
What if scientists could anticipate volcanic eruptions as they predict the weather? While determining rain or shine days in advance is more difficult, weather reports become more accurate on shorter time scales. A similar approach with volcanoes could make a big impact. Just one unforeseen eruption can result in tens of thousands of lives lost. If scientists could reliably predict when a volcano will next erupt, evacuations could be more timely and the damage mitigated.

Currently, scientists often identify “time to eruption” by surveying volcanic tremors from seismic signals. In some volcanoes, this intensifies as volcanoes awaken and prepare to erupt. Unfortunately, patterns of seismicity are difficult to interpret. In very active volcanoes, current approaches predict eruptions some minutes in advance, but they usually fail at longer-term predictions.

In [36]:
import pandas as pd
import numpy as np

In [3]:
df_eruption = pd.read_csv("/content/eruptions.csv")
df_event = pd.read_csv("/content/events.csv")
df_volcano = pd.read_csv("/content/volcano.csv")
df_sulfur = pd.read_csv("/content/sulfur.csv")
df_tree_rings = pd.read_csv("/content/tree_rings.csv")

In [27]:
df_eruption.head(50)

,volcano_number,volcano_name,eruption_number,eruption_category,area_of_activity,vei,start_year,start_month,start_day,evidence_method_dating,end_year,end_month,end_day,latitude,longitude
0,266030,Soputan,22354,Confirmed Eruption,NaN,NaN,2020.0,3.0,23.0,Historical Observations,2020.0,4.0,2.0,1.112,124.737
1,343100,San Miguel,22355,Confirmed Eruption,NaN,NaN,2020.0,2.0,22.0,Historical Observations,2020.0,2.0,22.0,13.434,-88.269
2,233020,"Fournaise, Piton de la",22343,Confirmed Eruption,NaN,NaN,2020.0,2.0,10.0,Historical Observations,2020.0,4.0,6.0,-21.244,55.708
3,345020,Rincon de la Vieja,22346,Confirmed Eruption,NaN,NaN,2020.0,1.0,31.0,Historical Observations,2020.0,4.0,17.0,10.830,-85.324
4,353010,Fernandina,22347,Confirmed Eruption,NaN,NaN,2020.0,1.0,12.0,Historical Observations,2020.0,1.0,12.0,-0.370,-91.550
5,273070,Taal,22344,Confirmed Eruption,NaN,NaN,2020.0,1.0,12.0,Historical Observations,2020.0,1.0,22.0,14.002,120.993
6,282050,Kuchinoerabujima,22345,Confirmed Eruption,NaN,NaN,2020.0,1.0,11.0,Historical Observations,2020.0,4.0,17.0,30.443,130.217
7,241040,Whakaari/White Island,22338,Confirmed Eruption,1978/90 Crater Complex,2.0,2019.0,12.0,9.0,Historical Observations,2019.0,12.0,9.0,-37.520,177.180
8,311060,Semisopochnoi,22341,Confirmed Eruption,NaN,NaN,2019.0,12.0,7.0,Historical Observations,2020.0,3.0,15.0,51.930,179.580
9,284096,Nishinoshima,22340,Confirmed Eruption,NaN,1.0,2019.0,12.0,5.0,Historical Observations,2020.0,4.0,17.0,27.247,140.874
10,311240,Cleveland,22342,Uncertain Eruption,NaN,NaN,2019.0,11.0,7.0,Historical Observations,2019.0,12.0,7.0,52.825,-169.944
11,282060,Kikai,22339,Confirmed Eruption,NaN,NaN,2019.0,11.0,2.0,Historical Observations,2020.0,4.0,16.0,30.793,130.305
12,300260,Klyuchevskoy,22335,Confirmed Eruption,NaN,NaN,2019.0,10.0,24.0,Historical Observations,2020.0,4.0,17.0,56.056,160.642
13,243070,Lateiki,22334,Confirmed Eruption,NaN,1.0,2019.0,10.0,13.0,Historical Observations,2019.0,10.0,22.0,-19.180,-174.870
14,283110,Asamayama,22326,Confirmed Eruption,NaN,NaN,2019.0,8.0,7.0,Historical Observations,2019.0,8.0,25.0,36.406,138.523
15,357090,Copahue,22336,Confirmed Eruption,NaN,NaN,2019.0,8.0,2.0,Historical Observations,2019.0,11.0,12.0,-37.856,-71.183
16,263090,Tangkuban Parahu,22325,Confirmed Eruption,NaN,NaN,2019.0,7.0,26.0,Historical Observations,2019.0,9.0,17.0,-6.770,107.600
17,311360,Shishaldin,22330,Confirmed Eruption,Summit crater,NaN,2019.0,7.0,23.0,Historical Observations,2020.0,4.0,9.0,54.756,-163.970
18,351020,"Ruiz, Nevado del",22329,Confirmed Eruption,NaN,NaN,2019.0,7.0,23.0,Historical Observations,2020.0,4.0,13.0,4.892,-75.324
19,311060,Semisopochnoi,22328,Confirmed Eruption,NaN,NaN,2019.0,7.0,16.0,Historical Observations,2019.0,8.0,24.0,51.930,179.580
20,252120,Ulawun,22319,Confirmed Eruption,NaN,NaN,2019.0,6.0,26.0,Historical Observations,2019.0,10.0,5.0,-5.050,151.330
21,354020,Ubinas,22324,Confirmed Eruption,NaN,NaN,2019.0,6.0,24.0,Historical Observations,2019.0,12.0,24.0,-16.355,-70.903
22,290250,Raikoke,22321,Confirmed Eruption,NaN,NaN,2019.0,6.0,22.0,Historical Observations,2019.0,7.0,1.0,48.292,153.250
23,233020,"Fournaise, Piton de la",22318,Confirmed Eruption,NaN,NaN,2019.0,6.0,11.0,Historical Observations,2019.0,10.0,27.0,-21.244,55.708
24,311120,Great Sitkin,22322,Confirmed Eruption,NaN,NaN,2019.0,6.0,1.0,Historical Observations,2019.0,6.0,7.0,52.076,-176.130
25,290240,Sarychev Peak,22320,Confirmed Eruption,NaN,2.0,2019.0,5.0,16.0,Historical Observations,2019.0,10.0,7.0,48.092,153.200
26,341040,Colima,22323,Confirmed Eruption,NaN,NaN,2019.0,5.0,11.0,Historical Observations,2019.0,7.0,12.0,19.514,-103.620
27,282110,Asosan,22317,Confirmed Eruption,NaN,NaN,2019.0,4.0,16.0,Historical Observations,2020.0,4.0,17.0,32.884,131.104
28,300260,Klyuchevskoy,22310,Confirmed Eruption,NaN,NaN,2019.0,4.0,9.0,Historical Observations,2019.0,7.0,2.0,56.056,160.642
29,352090,Sangay,22312,Confirmed Eruption,NaN,NaN,2019.0,3.0,26.0,Historical Observations,2020.0,4.0,17.0,-2.005,-78.341
30,344020,San Cristobal,22311,Confirmed Eruption,NaN,NaN,2019.0,3.0,4.0,Historical Observations,2019.0,3.0,4.0,12.702,-87.004
31,233020,"Fournaise, Piton de la",22307,Confirmed Eruption,NaN,NaN,2019.0,2.0,18.0,Historical Observations,2019.0,3.0,10.0,-21.244,55.708
32,263310,Tengger Caldera,22306,Confirmed Eruption,Bromo,2.0,2019.0,2.0,18.0,Historical Observations,2019.0,7.0,28.0,-7.942,112.950
33,300130,Karymsky,22309,Confirmed Eruption,NaN,NaN,2019.0,2.0,16.0,Historical Observations,2019.0,9.0,24.0,54.049,159.443
34,345040,Poas,22303,Confirmed Eruption,NaN,NaN,2019.0,2.0,7.0,Historical Observations,2019.0,9.0,30.0,10.200,-84.233
35,261080,Sinabung,22316,Confirmed Eruption,NaN,NaN,2019.0,2.0,6.0,Historical Observations,2019.0,6.0,9.0,3.170,98.392
36,256010,Tinakula,22313,Confirmed Eruption,NaN,2.0,2018.0,12.0,8.0,Historical Observations,2020.0,4.0,11.0,-10.386,165.804
37,267020,Karangetang,22294,Confirmed Eruption,NaN,2.0,2018.0,11.0,25.0,Historical Observations,2020.0,4.0,17.0,2.781,125.407
38,357040,Planchon-Peteroa,22297,Confirmed Eruption,NaN,1.0,2018.0,11.0,7.0,Historical Observations,2019.0,5.0,7.0,-35.223,-70.568
39,351020,"Ruiz, Nevado del",22298,Uncertain Eruption,NaN,NaN,2018.0,10.0,26.0,Historical Observations,2018.0,10.0,26.0,4.892,-75.324
40,282050,Kuchinoerabujima,22296,Confirmed Eruption,NaN,3.0,2018.0,10.0,21.0,Historical Observations,2019.0,2.0,3.0,30.443,130.217
41,268060,Gamalama,22295,Confirmed Eruption,NaN,1.0,2018.0,10.0,4.0,Historical Observations,2018.0,10.0,6.0,0.800,127.330
42,266030,Soputan,22293,Confirmed Eruption,NaN,3.0,2018.0,10.0,2.0,Historical Observations,2018.0,12.0,16.0,1.112,124.737
43,260010,Barren Island,22292,Confirmed Eruption,NaN,1.0,2018.0,9.0,25.0,Historical Observations,2020.0,4.0,16.0,12.278,93.858
44,252120,Ulawun,22286,Confirmed Eruption,NaN,2.0,2018.0,9.0,21.0,Historical Observations,2018.0,10.0,12.0,-5.050,151.330
45,290200,Ketoi,22287,Uncertain Eruption,NaN,1.0,2018.0,9.0,21.0,Historical Observations,2018.0,9.0,21.0,47.350,152.475
46,290240,Sarychev Peak,22288,Confirmed Eruption,NaN,2.0,2018.0,9.0,8.0,Historical Observations,2018.0,10.0,15.0,48.092,153.200
47,311060,Semisopochnoi,22289,Confirmed Eruption,NaN,1.0,2018.0,9.0,8.0,Historical Observations,2018.0,10.0,31.0,51.930,179.580
48,312070,Veniaminof,22290,Confirmed Eruption,NaN,1.0,2018.0,9.0,4.0,Historical Observations,2018.0,12.0,23.0,56.170,-159.380
49,290390,Alaid,22281,Confirmed Eruption,NaN,1.0,2018.0,8.0,20.0,Historical Observations,2018.0,8.0,21.0,50.861,155.565

In [20]:
df_eruption.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11178 entries, 0 to 11177
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   volcano_number          11178 non-null  int64
 1   volcano_name            11178 non-null  object
 2   eruption_number         11178 non-null  int64
 3   eruption_category       11178 non-null  object
 4   area_of_activity        4694 non-null   object
 5   vei                     8272 non-null   float64
 6   start_year              11177 non-null  float64
 7   start_month             10985 non-null  float64
 8   start_day               10982 non-null  float64
 9   evidence_method_dating  9898 non-null   object
 10  end_year                4332 non-null   float64
 11  end_month               4329 non-null   float64
 12  end_day                 4326 non-null   float64
 13  latitude                11178 non-null  float64
 14  longitude               11178 non-null  float64
dtypes: float64(9), int64(2), object(4)
memory usage: 1.3+ MB

In [25]:
df_eruption.isnull().sum()

volcano_number               0
volcano_name                 0
eruption_number              0
eruption_category            0
area_of_activity          6484
vei                       2906
start_year                   1
start_month                193
start_day                  196
evidence_method_dating    1280
end_year                  6846
end_month                 6849
end_day                   6852
latitude                     0
longitude                    0
dtype: int64

In [39]:
df_eruption['evidence_method_dating'].value_counts()

evidence_method_dating
Historical Observations      6351
Tephrochronology             1043
Radiocarbon (uncorrected)     981
Radiocarbon (corrected)       852
Varve Count                   187
Ice Core                      116
Hydrophonic                    67
Magnetism                      58
Anthropology                   37
Uranium-series                 31
Ar/Ar                          29
Surface Exposure               29
Potassium-Argon                22
Dendrochronology               15
Thermoluminescence             11
Hydration Rind                 11
Uncertain                       4
Seismicity                      3
Fission track                   3
Lichenometry                    2
Name: count, dtype: int64

In [38]:
cols_to_drop = [
    'evidence_method_dating', 'start_day', 'start_month',
    ''
]

TypeError: Choicelist and default value do not have a common dtype: The DType <class 'numpy.dtypes._PyFloatDType'> could not be promoted by <class 'numpy.dtypes.StrDType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes._PyFloatDType'>)